### ISSUE TITLE
Plugin no longer works

### ISSUE THREAD

**Issue by domre77** [SteidlD/homebridge-inkbird-bt-thsensor#23]
Plugin not reading temp since HB 1.5.1, or returning a zero reading. 

From the HB log…

[27/10/2022, 12:59:35] [Hot water tank
] Info - Sending internal sensor
[27/10/2022, 12:59:35] [homebridge-ink bird-bt-thsensor] This plugin generate da warning from the characteristic
'E
xternal Sensor': characteristic value expected boolean and received undefine
d. See https:/ /homebridge.io/w/JtMGR £ or more info.
[27/10/2022,
12:59:35] [Hot water tank
] Info - Sending battery level undefin ed%
[27/10/2022, 12:59:35] [homebridge-ink bird-bt-thsensor] This plugin generate da warning from the characteristic
'B
attery Level': characteristic value ex pected valid finite number and receive d "undefined" (undefined). See https:/ /homebridge.io/w/JtMGR for more info.

**Comment by SteidlD** [comment]
Hi @claymca72,

The plugin is not broken. It runs fine on my system:
- Raspberry Pi 3B
- Running Hoobs V4.3.0 (which is actually quite new). This Hoobs version runs on:
   - Node Version 16.20.1
   - Homebridge Version 1.6.0

I don't think it has anything to do with the version of homebridge. The problem seems to be that your homebridge device doesn't receive BLE frames from your sensor at this time -> you can see the value undefined values: the plugin sends "undefined" if it couldn't receive anything, because I thought thats correcter than 0 - as zero could be a valid temperature also.
But homebrige or Apple Home makes 0 out of it anyway.

I think with some version of homebridge they just added this error messages, because earlier they didn't show up even though the plugin always sent undefined if no sensor reading was possible...
