### ISSUE TITLE
Mac mini 

### ISSUE THREAD

**Issue by claymca72** [SteidlD/homebridge-inkbird-bt-thsensor#25]
Has anyone had any luck with getting this to work on a Mac. I can get the sensors added but never can get a connection. I get the message that Homebridge is waiting for the Bluetooth device to power on.

**Comment by domre77** [comment]
The plugin is broken, but it doesn’t appear that anyone is actively maintaining it.

**Comment by SteidlD** [comment]
Hi @claymca72,

sorry for the late answer...
I'm quite sure your problem is caused by a different bluetooth hardware in the Mac mini. The message states that it is waiting for the Bluetooth hardware to power on. This is a message coming from the Bluetooth drivers. I didn't develop those but use the @abandonware/noble package. You'd have to look for a solution there I think. Difficult to help you anyway as I don't own a Mac mini, so I couldn't test this at all....

**Comment by claymca72** [comment]
Thanks for the reply. But I am now running homebridge on under unbuntu
